### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Spikechrisgaming** [minotar/imgd#150]
When ever i do go get it says go install: no install directory c:/Users/User/imgd outside GOPATH

**Comment by LukeHandle** [comment]
The issue is that imgd is not in the GOPATH. This would normally be solved by the (Linux) instructions of changing the path to the current directory (`pwd`). 

If you haven't already you need to set a GOPATH for you golang environment. The golang getting started docs give information on that. 

Once it is set, you can just do `go get github.com/minotaur/imgd`  and that should work.

**Comment by Spikechrisgaming** [comment]
What do you mean by that?

**Comment by clone1018** [comment]
Start here :) https://golang.org/doc/code.html
