### ISSUE TITLE
Skin doesn't update

### ISSUE THREAD

**Issue by Jannik8500** [minotar/imgd#176]
The Skin of the user "MrDeadForceLP" doesn't update since about 2 weeks.

Here's the url, I use: https://minotar.net/avatar/MrDeadForceLP/100
The MojangAPI returns a skin: https://sessionserver.mojang.com/session/minecraft/profile/a6e78911b8f940679fe377a790f46569

And mc-heads works as well: http://mc-heads.net/avatar/MrDeadForceLP/100

**Comment by MisterFixx** [comment]
While MCHeads adds the helmet element automatically, Minotar doesn't, use: https://minotar.net/helm/MrDeadForceLP/100 for the desired result.

**Comment by Jannik8500** [comment]
Hmm yes, but that wasn't the problem.
If you use my old url (https://minotar.net/avatar/MrDeadForceLP/100), you see the skin.
As I reported this bug, there wasn't a skin. 
So, this isn't the problem.

**Comment by LukeHandle** [comment]
Honestly, I missed this issue when you were seeing it :/

Did it match this skin? https://s3.amazonaws.com/MinecraftSkins/MrDeadForceLP.png Or just a long cached skin? Theoretically, we could end up with a skin cached for up to like, 4 days I think? But that is perfect storm.

I've seen other reported strangeness though with edge-cases and skins, so it is possible an issue is afoot.

**Comment by CoolDude53** [comment]
Still experiencing this problem, will update if the skin ever gets recached and updates to what it should be.

**Comment by LukeHandle** [comment]
Going to close this one out. User has since changed their name "MrDeadForceLP" -> "BagoBAM":

https://sessionserver.mojang.com/session/minecraft/profile/a6e78911b8f940679fe377a790f46569

Decodes to:
`{"timestamp":1478653057200,"profileId":"a6e78911b8f940679fe377a790f46569","profileName":"BagoBAM","textures":{"SKIN":{"url":"http://textures.minecraft.net/texture/72f998f1de3f871c3f4de81744d9cb146f3b4b37bc18f5e3f57f620a9cfd4db"}}}`

Which matches https://minotar.net/armour/body/BagoBAM
