### ISSUE TITLE
Add support for Ely.by

### ISSUE THREAD

**Issue by LucesEnBabel** [minotar/imgd#180]
This is a feature request.

If you can add support for Ely.by it would be great.

They have an API to extract user textures here
http://docs.ely.by/skin-system.html (russian, but understandable)

Thanks in advance

**Comment by MisterFixx** [comment]
Is this basically an alternative to Mojang's official skins servers?
I do speak and read russian bu i couldn't quite figure out what exactly this is for.

**Comment by LucesEnBabel** [comment]
Yes, it's an alternative Skin Server.

**Comment by MisterFixx** [comment]
It would seem very reduntant to add support to an alternative skin server just so you could use minotar, i doubt too many people would use that feature, instead what i would recommend you to do is set up your own version of minotar and modify it to retrieve skins from ely.by, you don't even have to use minotar, you can get a simple php based avatar script from github and just modify the URL from which it retrieves the skins, it's really not that difficult.

**Comment by LukeHandle** [comment]
What clients use this skin server?

**Comment by MisterFixx** [comment]
@LukeHandle From what the first few lines of the docs says:
"Ely.by is not to be used as a replacement for mojang's official skin server, but as an addition to them, so that so that players who bought minecraft don't lose their skin, and players of the cracked version can give themselves a skin."
It looks to me as though in Russia it is very common for large minecraft communities to create a custom minecraft clients for their servers, and most of the time that client is cracked, so they want to give their users skins, and so this Ely.by service could serve that purpose i guess. 
However i really see no point in adding support for that as this is an open source project so anyone can just clone it and do whatever they want with it themselves and then run it on their own server.

**Comment by LukeHandle** [comment]
Yea, closing out.
