### ISSUE TITLE
Skins not loading 

### ISSUE THREAD

**Issue by ExZiByte** [minotar/imgd#184]
Up till recently my webpage with about 11 minecraft skin heads was loading just fine now only 3 of them are working even if I manually go to get the picture myself (navigating to https://minotar.net/helm/{playername}) it just shows the steve skin unless its one of the 3 that work on my webpage.

**Comment by LukeHandle** [comment]
Hey there,

Apologies for the issues seen here. This is due to a change in the Mojang API and rate limits which they enforce on the replacement APIs.

We are currently tracking this over in https://github.com/minotar/imgd/issues/181

I have deployed some mitigation which has been working flawlessly for 2 hours (though in our non-peak times). I will be working further on this over the coming weeks on a more sustainable method (running 8x more servers is significant cost, especially when they are all utilised at less than 2%).

Anyway, I'll close this out in favour of the other Issue, apologies again for the inconvenience and impact you have seen here.
