### ISSUE TITLE
UUID with dashes does not redirect if size is provided

### ISSUE THREAD

**Issue by FireController1847** [minotar/imgd#210]
Don't know if this is a bug or not, but wanted to report it just in case it is. The following URL works:

https://minotar.net/helm/ddbbe2ed-d3a6-478e-a16a-a9944c4e0a70
![](https://minotar.net/helm/ddbbe2ed-d3a6-478e-a16a-a9944c4e0a70)

The following URL does not:

https://minotar.net/helm/ddbbe2ed-d3a6-478e-a16a-a9944c4e0a70/2048.png
![](https://minotar.net/helm/ddbbe2ed-d3a6-478e-a16a-a9944c4e0a70/2048.png)

However, uses the non-dashed version it does work with the size. Just wanted to let you guys know, feel free to close this if it isn't a bug.

**Comment by LukeHandle** [comment]
This arguably is a bug, yes. Did you notice this previously working, or something you came across while trying to use the service?

I'm fairly sure it used to redirect, I think a regression with the version4 changes.

**Comment by FireController1847** [comment]
I do believe it redirected previously and has stopped working, however the timeframe since I last uses this endpoint (and up to noticing the bug) is about a year

**Comment by LukeHandle** [comment]
Ahh - it's a slight difference in behaviour, but not quite a full bug. The max width is 300 - the redirect was correctly configured for a 3 digit width, not 4 digit (even though we don't error on a 4 digit width).

I've correctly it so that the behaviour is the same between them and a 4 digit width will now redirect (though the max is still just 300).
