### ISSUE TITLE
Better cache headers

### ISSUE THREAD

**Issue by confuser** [minotar/imgd#85]
Make use of an ETag, Expires and Last-Modified headers within the response header for optimised caching at the browser level.

Whilst they are being cached at the CDN level, all requests respond with 200 OK which means browsers are downloading the image whether it has changed or not.

They should be returning a 304 response after the initial request.

**Comment by LukeHandle** [comment]
I'm going to close this. ETags are being respected going through CloudFlare and it has been fixed in nginx so should make its way into whatever update the backend needs (sometime...)

Also, working Etags should be ideal for our situation where we can't store the skin for ever and we don't actually know the last modified whereas we can always compute the Hash and establish whether we need to re-transmit the new skin to the client.
